name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # run only when pushing to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Inject Supabase secrets into index.html
        run: |
          sed -i "s|SUPABASE_URL_PLACEHOLDER|${{ secrets.SUPABASE_URL }}|" index.html
          sed -i "s|SUPABASE_ANON_KEY_PLACEHOLDER|${{ secrets.SUPABASE_ANON_KEY }}|" index.html

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: .   # deploy everything (index.html + assets)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
